[pytest]
addopts = -W "ignore:.*allowed_objects.*:Warning" -W "ignore:.*ast\.NameConstant is deprecated.*:DeprecationWarning"
norecursedirs = scripts
filterwarnings =
    ignore:.*allowed_objects.*:Warning:langgraph\..*
    ignore:.*ast\.NameConstant is deprecated.*:DeprecationWarning:reportlab\..*
